src/beermasters/urls.py
from django.contrib import admin
from django.urls import path, include
from competitions.views import index, profile

urlpatterns = [
    path('', index, name='index'),
    path('competitions/', include('competitions.urls')),
    path('admin/', admin.site.urls),
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile', index, name="accounts_index"),
    path('accounts/profile/', index, name="accounts_index"),
]

admin.site.site_header = "BeerMasters!"
admin.site.site_title = "BeerMasters Baby!!"
admin.site.index_title = "Welcome to BeerMasters"

src/competitions/urls.py
from django.urls import path
from . import views

# TODO: fix URL's to make semantic sense
urlpatterns = [
    # Competitions
    path('', views.index, name='index'),
    path('add', views.competition, name='index'),
    path('<int:contest_id>/', views.detail, name='detail'),
    #path('<int:contest_id>/scoresheet', views.scoresheet, name='scoresheet'),
    path('<int:table_item_id>/score', views.score, name='score'),

    # Tables
    path('table/<int:table_id>', views.table, name='table'),
    path('table/<int:table_id>/item/scoresheet/<int:item_id>', views.scoresheet, name='scoresheet'),

    # Users
    path('register/', views.register, name='register'),
    path('profile/<int:user_id>', views.profile, name='profile'),

    # Breweries
    path('brewery/<int:brewery_id>', views.brewery_detail, name='brewery_detail'),
    path('brewery/add', views.brewery, name='brewery'),
    path('breweries/', views.breweries, name='breweries'),

    # Beers
    path('beers/', views.beers, name='beers'),
    path('beer/<int:beer_id>', views.beer_detail, name='beer_detail'),
    path('beer/add', views.beer, name='beer'),
]

src/competitions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.


# This are the breweries
class Brand(models.Model):
    date  = models.DateTimeField('Date of addition', default=timezone.now)
    name  = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.name

# This is the categories catalog
class BJCPcategory(models.Model):
    date     = models.DateTimeField('Date of addition', default=timezone.now)
    name     = models.TextField()
    def __str__(self):
        return self.name


# This is the styles catalog.
class BJCPstyle(models.Model):
    date     = models.DateTimeField('Date of addition', default=timezone.now)
    name     = models.TextField()
    category = models.ForeignKey(BJCPcategory, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.name

# This are the beers
class Item(models.Model):
    date  = models.DateTimeField('Date of addition', default=timezone.now)
    name  = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    style = models.ForeignKey(BJCPstyle, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.name

class Contest(models.Model):
    start_date = models.DateTimeField()
    end_date   = models.DateTimeField()
    name       = models.CharField(max_length=100)
    owner      = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    def __str__(self):
        return self.name

class Role(models.Model):
    name  = models.CharField(max_length=100)
    level = models.IntegerField(default=5)
    def __str__(self):
        return self.name

# In order to avoid confusing app Users versus django auth Users, we'll refer to
# the first ones as EndUsers, here we'll define the model
class EndUser(models.Model):
    user   = models.ForeignKey(User, unique=True, on_delete=models.DO_NOTHING)
    bjcp_id = models.CharField(max_length=15, blank=True, default='')
    elegibleforjudge = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username


# To avoid complexity on the database consider this sensorial attributes
# as objects, the rarely change so they can be table fields
# instead of creating an attribute table and more complex relations

class Aroma(models.Model):
    score         = models.IntegerField()
    malt          = models.IntegerField()
    hop           = models.IntegerField()
    fermentation  = models.IntegerField()
    other         = models.TextField()
    comment       = models.TextField()

class Apperance(models.Model):
    score     = models.IntegerField()
    color     = models.IntegerField()
    transp    = models.IntegerField()
    other     = models.TextField()
    comment   = models.TextField()

class Flavor(models.Model):
    score        = models.IntegerField()
    malt         = models.IntegerField()
    hop          = models.IntegerField()
    bitterness   = models.IntegerField()
    fermentation = models.IntegerField()
    balance      = models.IntegerField()
    final        = models.IntegerField()
    other        = models.TextField()
    comment      = models.TextField()

class Mouthfeel(models.Model):
    score       = models.IntegerField()
    body        = models.IntegerField()
    carbonation = models.IntegerField()
    warmth      = models.IntegerField()
    creaminess  = models.IntegerField()
    astringency = models.IntegerField()
    other       = models.TextField()
    comment     = models.TextField()


class DescriptorDefinition(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    def __str__(self):
        return self.name

class ContestParticipant(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.DO_NOTHING)
    user    = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    role    = models.ForeignKey(Role, on_delete=models.DO_NOTHING)
    def __str__(self):
        return "%s at %s (%s)" % (self.user, self.contest, self.role)
    
class ContestItem(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.DO_NOTHING)
    item    = models.ForeignKey(Item, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.item.name

class ContestCategory(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.DO_NOTHING)
    name    = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class ContestCategoryStyle(models.Model):
    contest_category = models.ForeignKey(ContestCategory, on_delete=models.DO_NOTHING)
    style            = models.ForeignKey(BJCPstyle, on_delete=models.DO_NOTHING)

class ContestTable(models.Model):
    contest  = models.ForeignKey(Contest, on_delete=models.DO_NOTHING)
    category = models.ForeignKey(ContestCategory, blank=True, null=True, on_delete=models.DO_NOTHING)
    name     = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class ContestTableItem(models.Model):
    table = models.ForeignKey(ContestTable, on_delete=models.DO_NOTHING)
    item  = models.ForeignKey(ContestItem, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.item.item.name

class ContestScoreSheet(models.Model):
    owner               = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    table_item          = models.ForeignKey(ContestTableItem, on_delete=models.DO_NOTHING)
    aroma               = models.ForeignKey(Aroma, on_delete=models.DO_NOTHING)
    apperance           = models.ForeignKey(Apperance, on_delete=models.DO_NOTHING)
    flavor              = models.ForeignKey(Flavor, on_delete=models.DO_NOTHING)
    mouthfeel           = models.ForeignKey(Mouthfeel, on_delete=models.DO_NOTHING)
    special_ingredients = models.CharField(max_length=200)
    bottle_insp         = models.NullBooleanField()
    bottle_insp_comment = models.TextField()
    overall_score       = models.IntegerField()
    overall_comment     = models.TextField()
    style               = models.IntegerField()
    technical           = models.IntegerField()
    intangible          = models.IntegerField()
    total_score         = models.IntegerField()
    def __str__(self):
        return "%s on %s" % (self.table_item.item.item.name, self.table_item.table.name)


class ContestScoreSheetDescriptor(models.Model):
    class Meta:
        unique_together = (('score_sheet', 'descriptor'),)

    score_sheet = models.ForeignKey(ContestScoreSheet, on_delete=models.DO_NOTHING)
    descriptor  = models.ForeignKey(DescriptorDefinition, on_delete=models.DO_NOTHING)

#class BjcpRank(models.Model):
#    name = models.CharField(max_length=100)
#    def __str__(self):
#        return self.name

#class UserBjcpInfo(models.Model):
#    bjcp_id = models.IntegerField(default=0)
#    bjcp_rank  = models.ForeignKey(BjcpRank, on_delete=models.DO_NOTHING)




#TODO check subcategories
#NAME = subcategory" type="text
#NAME = entry" type="text" value="{{ table_item.id }}" placeholder="Entry
#NAME = subcategory" type="text

src/competitions/forms.py
from django import forms
from competitions.models import EndUser

class BrewerapplyForm(forms.ModelForm):
    bjcp_id = forms.CharField(max_length=20)

    class Meta:
        model = EndUser
        fields = ('bjcp_id',)

src/competitions/templates/apperance_attributes.html
            {% load i18n %}
            <!-- Apperance Attributes -->


            <div class="form-group row">
                <div class="form-group col col-sm-8">
                    <label for="apperance" class="font-weight-bold">Apperance</label><small>(as appropriate for style)</small>
                </div>
                <div class="form-group col col-sm-2">
                    <input class="form-control" name="apperance_score" value="{{ apperance_score }}" type="text" placeholder="1-3" min="1" max="3" maxlength="1">
                </div>
            </div>
            <!-- TODO hide this stuff with the proper jquery function -->
            <div id="apperance-attribute-group">
	            <div class="form-group row border-bottom border-gray pb-1">
	                <div class="form-group col-3"></div>
	                <div class="form-group col">
	                    <label for="malt" class="font-weight-bold">{% trans 'Color' %}</label>
	                </div>
	                <div class="form-group col">
	                    <label for="malt" class="font-weight-bold">{% trans 'Light' %}</label>
	                </div>
	                <div class="form-group col text-right">
	                    <input class="form-check-input" type="radio" value="3" name="apperance_color" id="apperance_color-3" {% if apperance_color == '3' %}checked{% endif %}>
	                </div>
	                <div class="form-group col text-right">
	                    <input class="form-check-input" type="radio" value="2" name="apperance_color" id="apperance_color-2" {% if apperance_color == '2' %}checked{% endif %}>
	                </div>
	                <div class="form-group col text-right">
	                    <input class="form-check-input" type="radio" value="1" name="apperance_color" id="apperance_color-1" {% if apperance_color == '1' %}checked{% endif %}>
	                </div>
	                <div class="form-group col text-left">
	                    <label for="malt" class="font-weight-bold">{% trans 'Full' %}</label>
	                </div>
	            </div>
	
	            <div class="form-group row border-bottom border-gray pb-1">
	                <div class="form-group col"></div>
	                <div class="form-group col">
	                    <label for="malt" class="font-weight-bold">{% trans 'Transparency' %}</label>
	                </div>
	                <div class="form-group col">
	                    <label for="malt" class="font-weight-bold">{% trans 'Light' %}</label>
	                </div>
	                <div class="form-group col text-right">
	                    <input class="form-check-input" type="radio" value="3" name="apperance_transp" id="apperance_transp-3" {% if apperance_transp == '3' %}checked{% endif %}>
	                </div>
	                <div class="form-group col text-right">
	                    <input class="form-check-input" type="radio" value="2" name="apperance_transp" id="apperance_transp-2" {% if apperance_transp == '2' %}checked{% endif %}>
	                </div>
	                <div class="form-group col text-right">
	                    <input class="form-check-input" type="radio" value="1" name="apperance_transp" id="apperance_transp-1" {% if apperance_transp == '1' %}checked{% endif %}>
	                </div>
	                <div class="form-group col text-left">
	                    <label for="hop" class="font-weight-bold">{% trans 'Full' %}</label>
	                </div>
	            </div>
	
                <!-- TODO missing unreadable attributes from kilo's photos -->

	            <div class="form-group row border-bottom border-gray pb-1">
	                <div class="form-group col"></div>
	                <div class="form-group col-2 text-left">
	                    <label for="malt" class="font-weight-bold">{% trans 'Other' %}</label>
	                </div>
	                <div class="form-group col-8">
	                    <input class="form-control" name="apperance_other" value="{{ apperance_other }}" type="text" placeholder="Comment on Other">
	                </div>
	            </div>
                <div class="form-group row border-bottom border-gray pb-1">
	                <div class="form-group col"></div>
	                <div class="form-group col-2 text-left">
	                    <label for="malt" class="font-weight-bold">{% trans 'Texture' %}</label>
	                </div>
	                <div class="form-group col-8">
	                    <input class="form-control" name="apperance_texture" value="{{ apperance_texture }}" type="text" placeholder="Comment on Texture">
	                </div>
	            </div>

            </div>

            <div class="form-group row border-bottom border-gray pb-3">
                <div class="form-group col">
                    <small>Comment on color, clarity, and head (retention, color, and texture)</small>
                    <input class="form-control" name="apperance_comment" value="{{ apperance_comment }}"  type="text" placeholder="Comment on Apperance">
                </div>
            </div>

            <!-- /Apperance Attributes -->

src/competitions/templates/beers.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="my-3 p-3 bg-white rounded box-shadow">
	<div class="row">
		<div class="col-10">
            <h4 class="border-bottom border-gray pb-2 mb-1">{% trans 'Beers' %}</h4>
        </div>
		<div class="col-sm-2">
            <a href="/competitions/beer/add">{% trans 'New Beer' %}</a>
        </div>
    </div>
	<div class="row">
		<div class="col-sm-4">
    		<ul>
        	{% for beer in beers.all %}
        		<li><a href="/competitions/beer/{{ beer.id}}">{{ beer }}</a></li>
        	{% endfor %}
        	</ul>
		</div>
	</div>

</div>
{% endblock %}

src/competitions/templates/brewer_signup.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="my-3 p-3 bg-white rounded box-shadow">

    <h5 class="border-bottom border-gray pb-2 mb-0">{% trans 'Request Brewer Status' %}</h5>
    
    <form method="post">
    
        {% csrf_token %}

               
        <div class="form-group row pt-4">
            <div class="col-sm-1 mr-4">
                <label class="font-weight-bold" for="id_username">{% trans 'Username' %}:</label>
            </div>
            <div class="col-sm-3">
                <input type="text" class="form-control" name="username" size="20" autofocus required id="id_username" default="{{ id_username }}" editable=False >
            </div>
        </div>
    
       
    
    
        <div class="form-group row">
            <div class="col-sm-1 mr-4">
                <label class="font-weight-bold" for="id_bjcp_id">{% trans 'BJCP ID' %}:</label>
            </div>
            <div class="col-sm-3">
                <input class="form_control" type="text" name="bjcp_id" required id="id_bjcp_id">
            </div>
        </div>
    
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary mb-2">{% trans 'Apply' %}</button>
        </div>
    </form>
    
    </div>
{% endblock %}

src/competitions/templates/brewery.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="my-3 p-3 bg-white rounded box-shadow">
<h4 class="border-bottom border-gray pb-2 mb-2">{% trans 'Brewery' %}</h4>
<form method="post">

    {% csrf_token %}
<!--	
	<div class="form-group row pt-4">
		<div class="col-sm-2">
			<label class="font-weight-bold" for="owner">{% trans 'Owner' %}:</label>
		</div>
		<div class="col-sm-3">
            <input type="text" class="form-control" name="owner" size="20" autofocus required id="owner" value="{{ brewery.owner  }}" disabled>
		</div>
    </div>
-->
	<div class="form-group row">
		<div class="col-sm-2">
			<label class="font-weight-bold" for="name">{% trans 'Name' %}:</label>
		</div>
		<div class="col-sm-3">
            <input type="text" class="form-control" name="name" size="20" autofocus required id="name" value="{{ brewery.name }}" placeholder="{% trans 'Brewery Name' %}">
		</div>
	</div>

	{% if not brewery.owner.id or brewery.owner.id == request.user.id %}
	<div class="col-sm-1">
        <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
    </div>
	{% endif %}
</form>
	<div class="form-group row">
		<div class="col-sm-10">
    		<h5 class="border-bottom border-gray pb-2 mb-0">{% trans 'Beers' %}</h5> 
		</div>
		<div class="col-sm-2">
    		<a class="border-bottom border-gray pb-2 mb-0" href="/competitions/beer/add">{% trans 'New Beer' %}</a>
		</div>
	</div>

	{% if brewery.owner.id %}
	<div class="form-group row">
		<div class="col-sm-3">
    		<ul>
        	{% for beer in beers.all %}
        		<li><a href="/competitions/beer/{{ beer.id}}">{{ beer }}</a></li>
        	{% endfor %}
        	</ul>
		</div>
	</div>
	{% endif %}

</div>
{% endblock %}

src/competitions/templates/overall_attributes.html
            {% load i18n %}
            <!-- Overall Attributes -->

            <div class="form-group row">
                <div class="form-group col col-sm-8">
                    <label for="mouthfeel" class="font-weight-bold">Overall Impression</label><small>(as appropriate f  or style)</small>
                </div>
                <div class="form-group col col-sm-2">
                    <input class="form-control" name="overall_score" value="{{ overall_score }}"  type="text" placeholder="1-10" min="1" m  ax="10" maxlength="2">
                </div>
            </div>

            <div class="form-group row border-bottom border-gray pb-3">
                <div class="form-group col">
                    <small>Comment on overall drinking pleasure associated with entry, give suggestions for improvement</small>
                <input class="form-control" name="overall_comment" value="{{ overall_comment }}" type="text" placeholder="Comments on Overall Impression">
                </div>
            </div>

            <!-- /Overall Attributes -->

src/competitions/templates/register.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %}{% trans 'Register' %}{% endblock %}
{% block content %}
<div class="my-3 p-3 bg-white rounded box-shadow">

<h5 class="border-bottom border-gray pb-2 mb-0">{% trans 'Register' %}</h5>

<form method="post">

    {% csrf_token %}
	
	<div class="form-group row pt-4">
		<div class="col-sm-1 mr-4">
			<label class="font-weight-bold" for="id_username">{% trans 'Username' %}:</label>
		</div>
		<div class="col-sm-3">
    		<input type="text" class="form-control" name="username" size="20" autofocus required id="id_username" placeholder="{% trans 'Username' %}">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-1 mr-4">
			<label class="font-weight-bold" for="id_username">{% trans 'Email' %}:</label>
		</div>
		<div class="col-sm-3">
    		<input type="text" class="form-control" name="email" size="20" autofocus required id="id_email" placeholder="{% trans 'Email' %}">
		</div>
	</div>


	<div class="form-group row">
		<div class="col-sm-1 mr-4">
			<label class="font-weight-bold" for="id_password1">{% trans 'Password' %}:</label>
		</div>
		<div class="col-sm-3">
			<input class="form_control" type="password" name="password1" required id="id_password1">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-1 mr-4">
			<label class="font-weight-bold" for="id_password2">
			{% trans 'Password confirmation' %}:
			</label>
		</div>
		<div class="col-sm-2">
			<input class="form_control" type="password" name="password2" required id="id_password2">
			<span class="helptext">Enter the same password as before, for verification.</span>
		</div>
	</div>
	<div class="form-group">
    	<button type="submit" class="btn btn-primary mb-2">{% trans 'Register' %}</button>
	</div>
</form>

</div>
{% endblock %}

src/competitions/templates/ss_attributes.html
        <div class="col p-5 align-items-left">
            <div class="form-group">
                <div class="form-group row border-bottom border-gray pb-3">
                    <!-- TODO: add category and subcategory dropdown -->
                    <div class="form-check col">
                        <label for="category" class="font-weight-bold">Category #</label>
                        <input class="form-control" name="category" type="text" value="{{ table.category }}" readonly>
                    </div>
                    <div class="form-check col">
                        <label for="subcategory" class="font-weight-bold">Subcategory</label>
                        <input class="form-control" name="sub-category" type="text" value="{{ table_item.style.category }}" readonly>
                    </div>
                    <div class="form-check col">
                        <label for="entry" class="font-weight-bold">Entry #</label>
                        <input class="form-control" name="entry" type="text" value="{{ table_item.id }}" readonly>
                    </div>
                </div>
                <!--
                <div class="form-group row border-bottom border-gray pb-3">
                    <div class="form-check col">
                        <label for="subcategory" class="font-weight-bold">Subcategory (spell out)</label>
                        <input class="form-control" name="subcategory_txt" type="text" value="{{ subcategory_txt }}" placeholder="Subcategory">
                    </div>
                </div>
                -->
                
    
                <div class="form-group row border-bottom border-gray pb-3">
                    <div class="form-check col">
                        <label for="special-ingredients" class="font-weight-bold">Special Ingredients:</label>
                        <input class="form-control" name="special_ingredients" value="{{ score_sheet.special_ingredients }}" type="text" placeholder="Special Ingredients">
                    </div>
                </div>
                <div class="form-group row border-bottom border-gray pb-3">
                    <div class="form-check col">
                        <label for="bottle" class="pr-4 font-weight-bold">Bottle Inspection: </label>
                        <input class="form-check-input" type="checkbox" name="bottle_insp" id="bottle" {% if score_sheet.bottle_insp != None %}checked{% endif %}>
                        <small>Appropriate size, cap, fill level, label removal, etc.</small>
                        <br />
                        <small>Comments</small> 
                        <input class="form-control" name="bottle_insp_comment" value="{{ score_sheet.bottle_insp_comment }}" type="text" placeholder="Bottle">
                    </div>
                </div>
            </div>

src/competitions/templates/ss_descriptors.html
            <div class="form-group">
                <h5 class="border-bottom border-gray font-weight-bold">Descriptor Definitions (Mark all that apply):</h5>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Acetaldehyde" id="acetaldehyde" {% if ss_descriptors.Acetaldehyde != None %}checked{% endif%}>
                        <label class="form-check-label font-weight-bold" for="">Acetaldehyde</label> – Green apple-like aroma and flavor. Appearance (as appropriate for style)<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Alcoholic" id="alcoholic" {% if ss_descriptors.Alcoholic != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Alcoholic</label> – The aroma, flavor, and warming effect of ethanol and higher alcohols. Sometimes described as hot.<br />
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Astringent" id="astringent" {% if ss_descriptors.Astringent != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Astringent</label> – Puckering, lingering harshness and/or dryness in the finish/aftertaste; harsh graininess; huskiness.<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Diacetyl" id="diacetyl" {% if ss_descriptors.Diacetyl != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Diacetyl</label> – Artificial butter, butterscotch, or toffee aroma and flavor. Sometimes perceived as a slickness on the tongue.<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="DMS" id="dms" {% if ss_descriptors.DMS != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">DMS (dimethyl sulfide)</label> – At low levels a sweet, cooked or canned corn-like aroma and flavor.<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Estery" id="estery" {% if ss_descriptors.Estery != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Estery</label> – Aroma and/or flavor of any ester (fruits, fruit flavorings, or roses).<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Grassy" id="grassy" {% if ss_descriptors.Grassy != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Grassy</label> – Aroma/flavor of fresh-cut grass or green leaves.<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Light_struck" id="light_Struck" {% if ss_descriptors.Light_struck != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Light-Struck</label> – Similar to the aroma of a skunk. Mouthfeel (as appropriate for style)<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Metallic" id="metallic" {% if ss_descriptors.Metallic != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Metallic</label> – Tinny, coiny, copper, iron, or blood-like flavor.<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Oxidized" id="oxidized" {% if ss_descriptors.Oxidized != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Oxidized</label> – Any one or combination of stale, winy/vinous, cardboard, papery, or sherry-like aromas and flavors. <br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Phenolic" id="phenolic" {% if ss_descriptors.Phenolic != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Phenolic</label> – Spicy (clove, pepper), smoky, plastic, plastic adhesive strip, and/or medicinal (chlorophenolic). Overall Impression<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Musty" id="musty" {% if ss_descriptors.Musty != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Musty</label> – Stale, musty, or moldy aromas/flavors.
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Solvent" id="solvent" {% if ss_descriptors.Solvent != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Solvent</label> – Aromas and flavors of higher alcohols (fusel alcohols). Similar to acetone or lacquer thinner aromas.<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Sour_acidic" id="sour_acidic" {% if ss_descriptors.Sour_acidic != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Sour/Acidic</label> – Tartness in aroma and flavor. Can be sharp and clean (lactic acid), or vinegar-like (acetic acid).<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Sulfur" id="sulfur" {% if ss_descriptors.Sulfur != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Sulfur</label> – The aroma of rotten eggs or burning matches.<br />
                    </div>
    
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Vegetal" id="vegetal" {% if ss_descriptors.Vegetal != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Vegetal</label> – Cooked, canned, or rotten vegetable aroma and flavor (cabbage, onion, celery, asparagus, etc.)<br />
                    </div>
    
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="Yeasty" id="yeasty" {% if ss_descriptors.Yeasty != None %}checked{% endif %}>
                        <label class="form-check-label font-weight-bold" for="">Yeasty</label> – A bready, sulfury or yeast-like aroma or flavor.<br />
                    </div>
            </div>